package com.HangX.HangX_backend.controllers;

import com.HangX.HangX_backend.entity.Message;
import com.HangX.HangX_backend.entity.Room;
import com.HangX.HangX_backend.payload.AuthResponse;
import com.HangX.HangX_backend.payload.CreateRoomRequest;
import com.HangX.HangX_backend.payload.JoinRoomRequest;
import com.HangX.HangX_backend.payload.MessageDeleteEvent;
import com.HangX.HangX_backend.repository.RoomRepository;
import com.HangX.HangX_backend.security.JwtUtil;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;

import java.security.SecureRandom;
import java.util.List;

@RequestMapping("/api/v1/rooms")
@RestController
public class RoomController {

    // Word lists for human-friendly generated passwords  (format: word-word-NNN)
    private static final String[] ADJECTIVES = {
        "amber","arctic","bold","brave","bright","calm","cool","dark","deep",
        "eager","fast","fierce","fluid","fresh","grand","happy","icy","jade",
        "kind","lively","lunar","misty","noble","olive","prime","quiet","rapid",
        "royal","sharp","shiny","silent","silver","sleek","smart","solar","stern",
        "storm","sunny","swift","tender","urban","vivid","warm","wild","wise"
    };
    private static final String[] NOUNS = {
        "bear","bird","blaze","brook","cloud","comet","creek","dawn","deer",
        "dune","eagle","ember","falcon","flame","flash","forest","frost","gale",
        "grove","hawk","hill","jaguar","lake","leaf","lion","maple","moon",
        "nova","ocean","otter","peak","pine","rain","raven","ridge","river",
        "rock","rose","sage","shark","sky","snow","star","stone","storm",
        "tide","tiger","trail","wave","wolf"
    };

    private final RoomRepository       roomRepository;
    private final SimpMessagingTemplate messagingTemplate;
    private final PasswordEncoder       passwordEncoder;
    private final JwtUtil               jwtUtil;
    private final SecureRandom          secureRandom = new SecureRandom();

    public RoomController(RoomRepository roomRepository,
                          SimpMessagingTemplate messagingTemplate,
                          PasswordEncoder passwordEncoder,
                          JwtUtil jwtUtil) {
        this.roomRepository    = roomRepository;
        this.messagingTemplate = messagingTemplate;
        this.passwordEncoder   = passwordEncoder;
        this.jwtUtil           = jwtUtil;
    }

    // ── Create room ───────────────────────────────────────────────────────────

    /**
     * POST /api/v1/rooms
     * Body: { "roomId": "...", "password": "..." }   (password is optional)
     *
     * - If password is omitted/blank the server generates a secure random one.
     * - Stores the BCrypt hash; the plaintext is returned once and then gone.
     * - Issues a JWT scoped to this room for the creating user.
     *
     * The caller's userName is taken from the request body's userName field.
     * We re-use CreateRoomRequest for that; the frontend sends userName too.
     */
    @PostMapping()
    public ResponseEntity<?> createRoom(@RequestBody CreateRoomRequest req) {
        if (req.getRoomId() == null || req.getRoomId().isBlank()) {
            return ResponseEntity.badRequest().body("roomId is required");
        }
        if (roomRepository.findByRoomId(req.getRoomId()) != null) {
            return ResponseEntity.badRequest().body("Room already exists");
        }

        // Resolve plaintext password (caller-supplied or auto-generated)
        boolean autoGenerated = (req.getPassword() == null || req.getPassword().isBlank());
        String plaintext = autoGenerated ? generateSecurePassword() : req.getPassword().trim();

        Room room = new Room();
        room.setRoomId(req.getRoomId());
        room.setPasswordHash(passwordEncoder.encode(plaintext));
        roomRepository.save(room);

        String userName = (req.getUserName() != null && !req.getUserName().isBlank())
                ? req.getUserName().trim()
                : "creator";

        String token = jwtUtil.generateToken(userName, req.getRoomId());

        return ResponseEntity.status(HttpStatus.CREATED).body(
                new AuthResponse(
                        token,
                        req.getRoomId(),
                        userName,
                        autoGenerated ? plaintext : null   // show generated password once
                )
        );
    }

    // ── Join room ─────────────────────────────────────────────────────────────

    /**
     * POST /api/v1/rooms/{roomId}/join
     * Body: { "userName": "...", "password": "..." }
     *
     * Verifies the BCrypt hash; on success issues a JWT for this user+room.
     */
    @PostMapping("/{roomId}/join")
    public ResponseEntity<?> joinRoom(@PathVariable String roomId,
                                      @RequestBody JoinRoomRequest req) {
        Room room = roomRepository.findByRoomId(roomId);
        if (room == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Room not found");
        }

        if (req.getPassword() == null
                || !passwordEncoder.matches(req.getPassword(), room.getPasswordHash())) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Incorrect password");
        }

        String userName = (req.getUserName() != null && !req.getUserName().isBlank())
                ? req.getUserName().trim()
                : "guest";

        String token = jwtUtil.generateToken(userName, roomId);

        return ResponseEntity.ok(new AuthResponse(token, roomId, userName, null));
    }

    // ── Get paginated messages ────────────────────────────────────────────────

    @GetMapping("/{roomId}/messages")
    public ResponseEntity<List<Message>> getMessages(
            @PathVariable String roomId,
            @RequestParam(value = "page", defaultValue = "0",  required = false) int page,
            @RequestParam(value = "size", defaultValue = "20", required = false) int size
    ) {
        Room room = roomRepository.findByRoomId(roomId);
        if (room == null) return ResponseEntity.notFound().build();

        List<Message> messages = room.getMessages();
        int start = Math.max(0, messages.size() - (page + 1) * size);
        int end   = Math.min(start + size, messages.size());
        return ResponseEntity.ok(messages.subList(start, end));
    }

    // ── Delete a single message ───────────────────────────────────────────────

    /**
     * DELETE /api/v1/rooms/{roomId}/messages/{messageId}?sender={sender}
     * Requires a valid JWT in Authorization header (enforced by JwtAuthFilter).
     */
    @DeleteMapping("/{roomId}/messages/{messageId}")
    public ResponseEntity<?> deleteMessage(
            @PathVariable String roomId,
            @PathVariable String messageId,
            @RequestParam("sender") String sender
    ) {
        Room room = roomRepository.findByRoomId(roomId);
        if (room == null) return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Room not found");

        List<Message> messages = room.getMessages();
        Message target = messages.stream()
                .filter(m -> messageId.equals(m.getMessageId()))
                .findFirst()
                .orElse(null);

        if (target == null) return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Message not found");

        if (!sender.equals(target.getSender())) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("You can only delete your own messages");
        }

        messages.remove(target);
        roomRepository.save(room);

        messagingTemplate.convertAndSend(
                "/topic/room/" + roomId + "/delete",
                new MessageDeleteEvent(messageId, roomId, sender));

        return ResponseEntity.noContent().build();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private String generateSecurePassword() {
        // Format: adjective-noun-NNN  e.g. "swift-falcon-471"
        // Easy to read aloud, easy to share, still ~150 000 combinations
        String adj  = ADJECTIVES[secureRandom.nextInt(ADJECTIVES.length)];
        String noun = NOUNS[secureRandom.nextInt(NOUNS.length)];
        int    num  = 100 + secureRandom.nextInt(900); // 100–999
        return adj + "-" + noun + "-" + num;
    }
}
